document.writeln("<header class=\"main-header\">");
document.writeln("        <!-- Logo -->");
document.writeln("        <a href=\""+path+"/resources/index.html\" class=\"logo\" style=\"font-size:20pt;text-align:left;\"><b>CE-VIEW</b></a>");
document.writeln("        <!-- Header Navbar: style can be found in header.less -->");
document.writeln("        <nav class=\"navbar navbar-static-top\" role=\"navigation\">");
document.writeln("          <!-- Sidebar toggle button-->");
document.writeln("          <a href=\"#\" class=\"sidebar-toggle\" data-toggle=\"offcanvas\" role=\"button\">");
document.writeln("            <span class=\"sr-only\">Toggle navigation</span>");
document.writeln("          </a>");
document.writeln("          <div class=\"navbar-custom-menu\">");
document.writeln("            <ul class=\"nav navbar-nav\">");
//document.writeln("              <!-- Messages: style can be found in dropdown.less-->");
//document.writeln("              <li class=\"dropdown messages-menu\">");
//document.writeln("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">");
//document.writeln("                  <i class=\"fa fa-envelope-o\"></i>");
//document.writeln("                  <span class=\"label label-success\">4</span>");
//document.writeln("                </a>");
//document.writeln("                <ul class=\"dropdown-menu\">");
//document.writeln("                  <li class=\"header\">You have 4 messages</li>");
//document.writeln("                  <li>");
//document.writeln("                    <!-- inner menu: contains the actual data -->");
//document.writeln("                    <ul class=\"menu\">");
//document.writeln("                      <li><!-- start message -->");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <div class=\"pull-left\">");
//document.writeln("                            <img src=\"resources/dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\"/>");
//document.writeln("                          </div>");
//document.writeln("                          <h4>");
//document.writeln("                            Support Team");
//document.writeln("                            <small><i class=\"fa fa-clock-o\"></i> 5 mins</small>");
//document.writeln("                          </h4>");
//document.writeln("                          <p>Why not buy a new awesome theme?</p>");
//document.writeln("                        </a>");
//document.writeln("                      </li><!-- end message -->");
//document.writeln("                      <li>");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <div class=\"pull-left\">");
//document.writeln("                            <img src=\"resources/dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"user image\"/>");
//document.writeln("                          </div>");
//document.writeln("                          <h4>");
//document.writeln("                            AdminLTE Design Team");
//document.writeln("                            <small><i class=\"fa fa-clock-o\"></i> 2 hours</small>");
//document.writeln("                          </h4>");
//document.writeln("                          <p>Why not buy a new awesome theme?</p>");
//document.writeln("                        </a>");
//document.writeln("                      </li>");
//document.writeln("                      <li>");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <div class=\"pull-left\">");
//document.writeln("                            <img src=\"resources/dist/img/user4-128x128.jpg\" class=\"img-circle\" alt=\"user image\"/>");
//document.writeln("                          </div>");
//document.writeln("                          <h4>");
//document.writeln("                            Developers");
//document.writeln("                            <small><i class=\"fa fa-clock-o\"></i> Today</small>");
//document.writeln("                          </h4>");
//document.writeln("                          <p>Why not buy a new awesome theme?</p>");
//document.writeln("                        </a>");
//document.writeln("                      </li>");
//document.writeln("                      <li>");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <div class=\"pull-left\">");
//document.writeln("                            <img src=\"resources/dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"user image\"/>");
//document.writeln("                          </div>");
//document.writeln("                          <h4>");
//document.writeln("                            Sales Department");
//document.writeln("                            <small><i class=\"fa fa-clock-o\"></i> Yesterday</small>");
//document.writeln("                          </h4>");
//document.writeln("                          <p>Why not buy a new awesome theme?</p>");
//document.writeln("                        </a>");
//document.writeln("                      </li>");
//document.writeln("                      <li>");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <div class=\"pull-left\">");
//document.writeln("                            <img src=\"resources/dist/img/user4-128x128.jpg\" class=\"img-circle\" alt=\"user image\"/>");
//document.writeln("                          </div>");
//document.writeln("                          <h4>");
//document.writeln("                            Reviewers");
//document.writeln("                            <small><i class=\"fa fa-clock-o\"></i> 2 days</small>");
//document.writeln("                          </h4>");
//document.writeln("                          <p>Why not buy a new awesome theme?</p>");
//document.writeln("                        </a>");
//document.writeln("                      </li>");
//document.writeln("                    </ul>");
//document.writeln("                  </li>");
//document.writeln("                  <li class=\"footer\"><a href=\"#\">See All Messages</a></li>");
//document.writeln("                </ul>");
//document.writeln("              </li>");
//document.writeln("              <!-- Notifications: style can be found in dropdown.less -->");
//document.writeln("              <li class=\"dropdown notifications-menu\">");
//document.writeln("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">");
//document.writeln("                  <i class=\"fa fa-bell-o\"></i>");
//document.writeln("                  <span class=\"label label-warning\">10</span>");
//document.writeln("                </a>");
//document.writeln("                <ul class=\"dropdown-menu\">");
//document.writeln("                  <li class=\"header\">You have 10 notifications</li>");
//document.writeln("                  <li>");
//document.writeln("                    <!-- inner menu: contains the actual data -->");
//document.writeln("                    <ul class=\"menu\">");
//document.writeln("                      <li>");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <i class=\"fa fa-users text-aqua\"></i> 5 new members joined today");
//document.writeln("                        </a>");
//document.writeln("                      </li>");
//document.writeln("                      <li>");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <i class=\"fa fa-warning text-yellow\"></i> Very long description here that may not fit into the page and may cause design problems");
//document.writeln("                        </a>");
//document.writeln("                      </li>");
//document.writeln("                      <li>");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <i class=\"fa fa-users text-red\"></i> 5 new members joined");
//document.writeln("                        </a>");
//document.writeln("                      </li>");
//document.writeln("");
//document.writeln("                      <li>");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <i class=\"fa fa-shopping-cart text-green\"></i> 25 sales made");
//document.writeln("                        </a>");
//document.writeln("                      </li>");
//document.writeln("                      <li>");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <i class=\"fa fa-user text-red\"></i> You changed your username");
//document.writeln("                        </a>");
//document.writeln("                      </li>");
//document.writeln("                    </ul>");
//document.writeln("                  </li>");
//document.writeln("                  <li class=\"footer\"><a href=\"#\">View all</a></li>");
//document.writeln("                </ul>");
//document.writeln("              </li>");
//document.writeln("              <!-- Tasks: style can be found in dropdown.less -->");
//document.writeln("              <li class=\"dropdown tasks-menu\">");
//document.writeln("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">");
//document.writeln("                  <i class=\"fa fa-flag-o\"></i>");
//document.writeln("                  <span class=\"label label-danger\">9</span>");
//document.writeln("                </a>");
//document.writeln("                <ul class=\"dropdown-menu\">");
//document.writeln("                  <li class=\"header\">You have 9 tasks</li>");
//document.writeln("                  <li>");
//document.writeln("                    <!-- inner menu: contains the actual data -->");
//document.writeln("                    <ul class=\"menu\">");
//document.writeln("                      <li><!-- Task item -->");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <h3>");
//document.writeln("                            Design some buttons");
//document.writeln("                            <small class=\"pull-right\">20%</small>");
//document.writeln("                          </h3>");
//document.writeln("                          <div class=\"progress xs\">");
//document.writeln("                            <div class=\"progress-bar progress-bar-aqua\" style=\"width: 20%\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">");
//document.writeln("                              <span class=\"sr-only\">20% Complete</span>");
//document.writeln("                            </div>");
//document.writeln("                          </div>");
//document.writeln("                        </a>");
//document.writeln("                      </li><!-- end task item -->");
//document.writeln("                      <li><!-- Task item -->");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <h3>");
//document.writeln("                            Create a nice theme");
//document.writeln("                            <small class=\"pull-right\">40%</small>");
//document.writeln("                          </h3>");
//document.writeln("                          <div class=\"progress xs\">");
//document.writeln("                            <div class=\"progress-bar progress-bar-green\" style=\"width: 40%\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">");
//document.writeln("                              <span class=\"sr-only\">40% Complete</span>");
//document.writeln("                            </div>");
//document.writeln("                          </div>");
//document.writeln("                        </a>");
//document.writeln("                      </li><!-- end task item -->");
//document.writeln("                      <li><!-- Task item -->");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <h3>");
//document.writeln("                            Some task I need to do");
//document.writeln("                            <small class=\"pull-right\">60%</small>");
//document.writeln("                          </h3>");
//document.writeln("                          <div class=\"progress xs\">");
//document.writeln("                            <div class=\"progress-bar progress-bar-red\" style=\"width: 60%\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">");
//document.writeln("                              <span class=\"sr-only\">60% Complete</span>");
//document.writeln("                            </div>");
//document.writeln("                          </div>");
//document.writeln("                        </a>");
//document.writeln("                      </li><!-- end task item -->");
//document.writeln("                      <li><!-- Task item -->");
//document.writeln("                        <a href=\"#\">");
//document.writeln("                          <h3>");
//document.writeln("                            Make beautiful transitions");
//document.writeln("                            <small class=\"pull-right\">80%</small>");
//document.writeln("                          </h3>");
//document.writeln("                          <div class=\"progress xs\">");
//document.writeln("                            <div class=\"progress-bar progress-bar-yellow\" style=\"width: 80%\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">");
//document.writeln("                              <span class=\"sr-only\">80% Complete</span>");
//document.writeln("                            </div>");
//document.writeln("                          </div>");
//document.writeln("                        </a>");
//document.writeln("                      </li><!-- end task item -->");
//document.writeln("                    </ul>");
//document.writeln("                  </li>");
//document.writeln("                  <li class=\"footer\">");
//document.writeln("                    <a href=\"#\">View all tasks</a>");
//document.writeln("                  </li>");
//document.writeln("                </ul>");
//document.writeln("              </li>");
//document.writeln("              <!-- User Account: style can be found in dropdown.less -->");
//document.writeln("              <li class=\"dropdown user user-menu\">");
//document.writeln("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">");
//document.writeln("                  <img src=\"resources/dist/img/user2-160x160.jpg\" class=\"user-image\" alt=\"User Image\"/>");
//document.writeln("                  <span class=\"hidden-xs\">Alexander Pierce</span>");
//document.writeln("                </a>");
//document.writeln("                <ul class=\"dropdown-menu\">");
//document.writeln("                  <!-- User image -->");
//document.writeln("                  <li class=\"user-header\">");
//document.writeln("                    <img src=\"resources/dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\" />");
//document.writeln("                    <p>");
//document.writeln("                      Alexander Pierce - Web Developer");
//document.writeln("                      <small>Member since Nov. 2012</small>");
//document.writeln("                    </p>");
//document.writeln("                  </li>");
//document.writeln("                  <!-- Menu Body -->");
//document.writeln("                  <li class=\"user-body\">");
//document.writeln("                    <div class=\"col-xs-4 text-center\">");
//document.writeln("                      <a href=\"#\">Followers</a>");
//document.writeln("                    </div>");
//document.writeln("                    <div class=\"col-xs-4 text-center\">");
//document.writeln("                      <a href=\"#\">Sales</a>");
//document.writeln("                    </div>");
//document.writeln("                    <div class=\"col-xs-4 text-center\">");
//document.writeln("                      <a href=\"#\">Friends</a>");
//document.writeln("                    </div>");
//document.writeln("                  </li>");
//document.writeln("                  <!-- Menu Footer-->");
//document.writeln("                  <li class=\"user-footer\">");
//document.writeln("                    <div class=\"pull-left\">");
//document.writeln("                      <a href=\"#\" class=\"btn btn-default btn-flat\">Profile</a>");
//document.writeln("                    </div>");
//document.writeln("                    <div class=\"pull-right\">");
//document.writeln("                      <a href=\"#\" class=\"btn btn-default btn-flat\">Sign out</a>");
//document.writeln("                    </div>");
//document.writeln("                  </li>");
//document.writeln("                </ul>");
//document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("        </nav>");
document.writeln("</header>");