document.writeln("<!-- Left side column. contains the logo and sidebar -->");
document.writeln("      <aside class=\"main-sidebar\">");
document.writeln("        <!-- sidebar: style can be found in sidebar.less -->");
document.writeln("        <section class=\"sidebar\">");
//document.writeln("          <!-- Sidebar user panel -->");
//document.writeln("          <div class=\"user-panel\">");
//document.writeln("            <div class=\"pull-left image\">");
//document.writeln("              <img src=\"resources/dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\" />");
//document.writeln("            </div>");
//document.writeln("            <div class=\"pull-left info\">");
//document.writeln("              <p>Alexander Pierce</p>");
//document.writeln("");
//document.writeln("              <a href=\"#\"><i class=\"fa fa-circle text-success\"></i> Online</a>");
//document.writeln("            </div>");
//document.writeln("          </div>");
//document.writeln("          <!-- search form -->");
//document.writeln("          <form action=\"#\" method=\"get\" class=\"sidebar-form\">");
//document.writeln("            <div class=\"input-group\">");
//document.writeln("              <input type=\"text\" name=\"q\" class=\"form-control\" placeholder=\"Search...\"/>");
//document.writeln("              <span class=\"input-group-btn\">");
//document.writeln("                <button type=\'submit\' name=\'search\' id=\'search-btn\' class=\"btn btn-flat\"><i class=\"fa fa-search\"></i></button>");
//document.writeln("              </span>");
//document.writeln("            </div>");
//document.writeln("          </form>");
//document.writeln("          <!-- /.search form -->");
document.writeln("          <!-- sidebar menu: : style can be found in sidebar.less -->");
document.writeln("          <ul class=\"sidebar-menu\">");
//document.writeln("            <li class=\"header\"><div style='font-weight:bold;margin:10px 0px 2px 0px;font-size:16pt;'>功能菜单</div></li>");
document.writeln("            <li>");
document.writeln("              <a href=\""+path+"/resources/views/test/test.html\">");
document.writeln("                <i class=\"fa fa-calendar\"></i> <span>AAAAA</span>");
document.writeln("              </a>");
document.writeln("            </li>");
//document.writeln("            <li>");
//document.writeln("              <a href=\""+path+"/resources/views/historylease/historylease.html\">");
//document.writeln("                <i class=\"fa fa-adjust\"></i> <span>历史租约管理</span>");
//document.writeln("              </a>");
//document.writeln("            </li>");
//document.writeln("            <li id='choosescopeandip'>");
//document.writeln("              <a href=\""+path+"/resources/views/scopeandip/scopeandip.html\">");
//document.writeln("                <i class=\"fa fa-table\"></i> <span>Scope管理+IP段管理</span>");
//document.writeln("              </a>");
//document.writeln("            </li>");
//document.writeln("            <li id='choosebasicconfig'>");
//document.writeln("              <a href=\""+path+"/resources/views/basicconfig/basicconfig.html\">");
//document.writeln("                <i class=\"fa fa-edit\"></i> <span>系统参数配置</span>");
//document.writeln("              </a>");
//document.writeln("            </li>");
//document.writeln("            <li id='choosebasicServerManager'>");
//document.writeln("              <a href=\""+path+"/resources/views/servermanager/servermanager.html\">");
//document.writeln("                <i class=\"fa fa-laptop\"></i> <span>系统服务管理</span>");
//document.writeln("              </a>");
//document.writeln("            </li>");
//document.writeln("            <li id='choosewhitelist'>");
//document.writeln("              <a href=\""+path+"/resources/views/whitelist/whitelist.html\">");
//document.writeln("                <i class=\"fa fa-newspaper-o\"></i> <span>白名单管理</span>");
//document.writeln("              </a>");
//document.writeln("            </li>");
document.writeln("			  <li class=\"treeview\">");
document.writeln("            	<a href=\"#configurationcreator\">");
document.writeln("            		<i class=\"fa fa-file-text\"></i> <span>BBBBB</span>");
document.writeln("            		<i class=\"fa fa-angle-left pull-right\"></i>");
document.writeln("            	</a>");
document.writeln("            	<ul class=\"treeview-menu\">");
document.writeln("            		<li>");
document.writeln("		              <a href=\""+path+"/resources/views/configurationcreator/configurationcreator.html\">");
document.writeln("		                <i class=\"fa fa-circle-o\"></i> <span>11111</span>");
document.writeln("		              </a>");
document.writeln("		            </li>");
document.writeln("            		<li>");
document.writeln("		              <a href=\""+path+"/resources/views/configurationendcreator/configurationendcreator.html\">");
document.writeln("		                <i class=\"fa fa-circle-o\"></i> <span>22222</span>");
document.writeln("		              </a>");
document.writeln("		            </li>");
document.writeln("            	</ul>");
document.writeln("            </li>");
//document.writeln("            <li>");
//document.writeln("              <a href=\""+path+"/resources/views/client/client.html\">");
//document.writeln("                <i class=\"fa fa-reorder\"></i> <span>Client</span>");
//document.writeln("              </a>");
//document.writeln("            </li>");
//document.writeln("            <li>");
//document.writeln("              <a href=\""+path+"/resources/views/clientclass/clientclass.html\">");
//document.writeln("                <i class=\"fa fa-sort-amount-desc\"></i> <span>Client Class</span>");
//document.writeln("              </a>");
//document.writeln("            </li>");
//document.writeln("            <li>");
//document.writeln("              <a href=\""+path+"/resources/views/policy/policy.html\">");
//document.writeln("                <i class=\"fa fa-cogs\"></i> <span>策略管理+Option管理</span>");
//document.writeln("              </a>");
//document.writeln("            </li>");
//document.writeln("            <li>");
//document.writeln("              <a href=\""+path+"/resources/views/staticip/staticip.html\">");
//document.writeln("                <i class=\"fa fa-code-fork\"></i> <span>静态IP设备绑定</span>");
//document.writeln("              </a>");
//document.writeln("            </li>");
document.writeln("          </ul>");
document.writeln("        </section>");
document.writeln("        <!-- /.sidebar -->");
document.writeln("      </aside>");